name: frontend
description: "RFID based access control system."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.14
  flutter_svg_provider: ^1.0.7
  google_nav_bar: ^5.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^1.2.1
  shared_preferences: ^2.2.2


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

